DROP TABLE IF EXISTS wcf1_guestbook_entry;
CREATE TABLE wcf1_guestbook_entry (
	entryID INT(10) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	username VARCHAR(255) NOT NULL DEFAULT '',
	subject VARCHAR(255) NOT NULL DEFAULT '',
	message MEDIUMTEXT,
	time INT(10) NOT NULL DEFAULT 0,
	enableSmilies TINYINT(1) NOT NULL DEFAULT 1,
	enableHtml TINYINT(1) NOT NULL DEFAULT 0,
	enableBBCodes TINYINT(1) NOT NULL DEFAULT 1,
	isDeleted TINYINT(1) NOT NULL DEFAULT 0,
	
	KEY (time)
);